version: "3.8"

services:
  angular-app:
    build:
      context: .
    container_name: angular-dashboard
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0
    networks:
      - my-first-network   

networks:
  my-first-network:        
    driver: bridge
